version: "3.7"

services:
  vault:
    image: 446481105531.dkr.ecr.us-east-2.amazonaws.com/key-vault:latest
    networks: 
      - vault
    tty: true
    restart: "on-failure"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN-DevVaultToken}
      ROOT_TOKEN_PATH: /vault/token/.root
      VAULT_ADDR: http://vault:8200
      PLUGIN_MOUNT_PATH: quorum
      VAULT_IS_READY: /vault/token/.ready
    ports:
      - 8200:8200
    volumes:
      - token:/vault/token
      - ./vault-init.sh:/usr/local/bin/init.sh
    entrypoint:
      - sh
      - -c
      - |
        apk add --no-cache curl
        chmod +x 400 /usr/local/bin/init.sh
        ( sleep 2 ; init.sh && cat > $${VAULT_IS_READY}) &
        vault server -dev -dev-plugin-dir=/vault/plugins/ -dev-listen-address="0.0.0.0:8200" -log-level=trace
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "--proxy",
          "off",
          "http://localhost:8200/v1/sys/health?standbyok=true",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s

networks:
  vault:
    driver: bridge

volumes:
  token:
    driver: local
