services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: "on-failure"
